site_name: When immunology meets bioinformatics

nav:
  - Home: index.md
  - Precourse preparations: precourse.md
  - Course schedule: course_schedule.md
  - Course material: course_material.md
  - Hands-on: hands_on.md

theme:
  name: material
  logo: assets/SIB_logo.svg
  favicon: assets/SIB_logo.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    tip: fontawesome/solid/bullhorn
  features:
    - announce.dismiss

# Repository
repo_name: sib-swiss/immunology-in-bioinformatics-training/
repo_url: https://github.com/sib-swiss/immunology-in-bioinformatics-training

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/consent.js

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our trainig material and whether users
      find what they're searching for. With your consent, you're helping us to
      make our training material better.
    cookies:
      matomo: Matomo Analytics
  
copyright: >
  Copyright &copy; 2021-2022 SIB Swiss institute of Bioinformatics â€“
